### ISSUE TITLE
Activate the wordpress localisation ?

### ISSUE THREAD

**Issue by xet7** [sandstormports/wordpress-sandstorm#17]
_From @jeau on March 6, 2016 9:26_

Hi

Why not activate the location of wordpress ?
I can not use Sandstorm as long as users can not use wordpress in their language.

another question ?
Why do not use the official repo which seem's up to date 
https://github.com/WordPress/WordPress

Thierry

_Copied from original issue: dwrensha/wordpress-sandstorm#23_

**Comment by xet7** [comment]
_From @dwrensha on March 7, 2016 18:42_

As I understand it, support for non-English languages in WordPress works a lot like plugins and themes do. To support French, for example, you need to add a bunch of files like `fr_FR.mo` and  `fr_FR.po` to the `wordpress/wp-content/languages` directory. Unfortunately, unlike with themes and plugins, WordPress does not seem to provide an easy way to upload the language files through a web interface; you seem to need direct access to the filesystem. The good news is that these files should fit in quite nicely with the app add-on feature that [we've talked about](https://github.com/sandstorm-io/sandstorm/issues/507) implementing for Sandstorm eventually. However, it's unclear when we'll get around to implementing that feature.

If you need support for other languages in the short term, maybe we should choose a set of commonly-needed languages and bundle them with our main Sandstorm app, so that everyone can use them. If we go this route, which languages do you think would be most important?

> Why do not use the official repo which seem's up to date

To get WordPress to work well with Sandstorm, we need to make some minor modifications. Ideally, these would all fit within a `sandstorm.php` must-use plugin, but there a few things I haven't yet figured out how to do that way (e.g. the initial installation flow).

**Comment by xet7** [comment]
_From @jeau on March 8, 2016 16:33_

Hi David

Thank you very much for your detailed answer.

For users, I need the French language. 
However, I think the most used languages will be needed quickly. Perhaps you can start by Spanish, French, Portuguese, and why not the Chinese and Arabic languages.

thanks in advance
Thierry

**Comment by xet7** [comment]
_From @paulproteus on August 30, 2016 16:43_

@dwrensha my advice is that we bundle the top 10 Internet languages:

http://www.internetworldstats.com/stats7.htm

Specifically:
- English
- Chinese (Traditional as well as Simplified)
- Spanish
- Arabic
- Portuguese
- Japanese
- Malay
- Russian
- French
- German

I know this might increase the size of the WordPress package, but I think in the increase in utility is substantial. What do you think?

There are a number of different resources on most-popular languages on the web, and different ways of measuring it. The different measurements produce vaguely similar results, and I think we have no thoughtful way to pick one measurement strategy over another, so I propose that you do the above, and if it suits @jeau 's needs, then we try to generalize that across other Sandstorm apps. If users request other languages, we can look into adding it to the list of languages we add as a matter of course.

Let me know what you think.

**Comment by xet7** [comment]
_From @dwrensha on August 30, 2016 18:3_

Sounds good to me. I think each language file is less than 1MB unpacked, this would not cause a huge amount of bloat. I'll look into this next time I update the WordPress package.

**Comment by jeau** [comment]
Yeah, I totally agree. Let's try this first set of languages. 
Great thanks

**Comment by JamborJan** [comment]
Hey @jeau tanks again for your help with the languages. I was able to create a build. To ensure that we are talking about the same result: it will now be possible to change the back-end language in WordPress for Sandstorm. This has no impact on the frontend and how visitors see a page. Okay?

Right now I'm still having an issue with the display of the language, there is no text but the code displayed in the settings view:
![bildschirmfoto 2018-09-03 um 14 25 08](https://user-images.githubusercontent.com/7508960/44986877-726c2000-af85-11e8-968c-d9120ac551d7.png)

If someone has an idea why that happens, please let me know. I'll do some testing with the new package and if I find a solution I'll include it otherwise I'll publish it with the code displayed.

Thanks

**Comment by jeau** [comment]
Hi @JamborJan 

Thanks for integrating these translations, I had seen this trick, and I tried to find a solution without success. I didn't look any further.

Outside Sandstorm, I think Wordpress uses some kind of webservice to get the list of available translations. In this case, Wordpress gets the labels. This is not the case when we put the files directly.

I'll do some investigation

**Comment by JamborJan** [comment]
Hey @jeau thanks for the quick reply.

One feedback from my tests so far: it's working quite well. The only not translated point so far are the Sandstorm publishing information:

![bildschirmfoto 2018-09-03 um 14 53 23](https://user-images.githubusercontent.com/7508960/44987910-2de28380-af89-11e8-92fc-c581f73e2d50.png)

They are based on this: https://github.com/sandstormports/wordpress-sandstorm/blob/2be74309593b8de40622e1a82591f2f87db2daa1/read-only-plugins/mu-plugins/sandstorm.php

As I'm not familiar with creating *.po and *.mo files I have no chance to build these files now. If you are familiar with that, feel free to do so. If not: do you think this small english part will matter?

Thanks.

**Comment by jeau** [comment]
hope I can do this work as soon as possible, the next few days

**Comment by JamborJan** [comment]
Again thanks a lot @jeau. I was able to build a test package: https://github.com/sandstormports/wordpress-sandstorm/releases/tag/15

You can use it for testing. It should not destroy anything but please backup all WordPress grains before using it.

**Comment by jeau** [comment]
thanks
I'm testing but currently I can't activate the localization correctly for this part
th

**Comment by jeau** [comment]
@JamborJan I have found a solution to this issue. I have to test it but I'm still busy. I will publish a PR this weekend

**Comment by JamborJan** [comment]
Dear @jeau thanks a lot for all your help with this. I've created a new package and published it also to the sandstorm app store. You can also find it here on github: https://github.com/sandstormports/wordpress-sandstorm/releases/tag/15

If there are any questions or if you have other ideas or requests for Wordpress on Sandstorm, please let me know.
