### ISSUE TITLE
Add Finnish FI translation

### ISSUE THREAD

**Issue by JamborJan** [sandstormports/wordpress-sandstorm#36]
As discussed with @xet7 we will add the Finnish (fi) [language pack](https://translate.wordpress.org/locale/fi).

@xet7 can you please edit [this file](https://github.com/sandstormports/wordpress-sandstorm/blob/master/read-only-plugins/mu-plugins/languages/sandstorm-integration-fi_FI.po) and translate the text parts into Finnish? Please asign the task to me when your done and I'll cfeate a new package.

**Comment by xet7** [comment]
Done.

**Comment by JamborJan** [comment]
![bildschirmfoto 2018-09-11 um 21 31 27](https://user-images.githubusercontent.com/7508960/45384000-08025200-b60d-11e8-8641-0d52326b41e5.png)

Thats a lot of [Umlaute](https://translate.google.com/#auto/fi/Umlaute)! Even the Finnish word for "Umlaute" has 3 times ä and an ö! What a beautiful language.

I've pushed a new version to the app store and added the same also here as release on github: https://github.com/sandstormports/wordpress-sandstorm/releases/tag/v16

Pidä hauskaa!
