### ISSUE TITLE
licensing server is unable to connect with my wp site

### ISSUE THREAD

**Issue by seyo-IV** [sandstormports/wordpress-sandstorm#41]
I have a plugin(FileManager and Backup Guard) installed on wp. Somehow I can't register the product because my site is unable to connect to the licensing server. Is there a reason for blocking it?

**Comment by xet7** [comment]
@seyo-IV 

What is link to those plugins?

**Comment by xet7** [comment]
I don't know what file manager is used for. It's already possible to add images etc to WordPress.

You can create backup of any Sandstorm grain like WordPress, Wekan etc by clicking arrow down button on top black menu bar.

**Comment by xet7** [comment]
Here is how backups are made at Sandstorm:
https://docs.sandstorm.io/en/latest/administering/backups/

There is no auto grain backup yet:
https://github.com/sandstorm-io/sandstorm/issues/1324

Sandstorm WordPress grain is only running when someone is logged into Sandstorm, and has opened WordPress grain for editing etc. It generates static website for website users. Sandstorm Wekan uses SQLite as database, not MySQL, so those plugins that assume MySQL do not work, they need fixing of database support.

For modifying WordPress website CSS etc, I do use this plugin, it works very well at Sandstorm WordPress:
https://wordpress.org/plugins/scripts-n-styles/

**Comment by ocdtrekkie** [comment]
The biggest issue @seyo-IV is having is particularly non-trivial to fix: Sandstorm is designed to prevent applications from "calling home", so it's near impossible for a plugin to talk to it's licensing server. Ideally Sandstorm would have a good feature for you to permit the server to talk to a specific domain so it could complete a licensing check, but that has not been implemented in the Sandstorm platform to my knowledge.

**Comment by xet7** [comment]
When you download Sandstorm Wekan grain, it's .zip file. You could unzip it, add license key, zip it and upload back to Sandstorm. But I don't know how to do it online directly.
