### ISSUE TITLE
Release 17 tends to hang on powerbox-http-proxy setup

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstormports/wordpress-sandstorm#46]
I am unsure what causes this, but it seems to happen for upgrades or sometimes on the second/additional launch of a grain that has previously worked correctly.

I'm guessing the proxy never creates the root cert, because it can't find the environment variable.

continue.sh is the related script here: https://github.com/sandstormports/wordpress-sandstorm/blob/master/continue.sh
but the environment variable is set in the pkgdef, here: https://github.com/sandstormports/wordpress-sandstorm/blob/master/.sandstorm/sandstorm-pkgdef.capnp

cc: @zenhack 

```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
waiting for root to be available at /var/ca-spoof-cert.pem.
2023/02/21 17:36:58 Error: environment variable "POWERBOX_WEBSOCKET_PORT" is not defined.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
waiting for root to be available at /var/ca-spoof-cert.pem.
```

**Comment by zenhack** [comment]
You probably need to set the same variables in the definition of `continueCommand`, below.

**Comment by ocdtrekkie** [comment]
...Wow. You know, I had no clue that there were two separate sets of environments there... I feel dumb. I'll fix it. :|

**Comment by ocdtrekkie** [comment]
Fixed by https://github.com/sandstormports/wordpress-sandstorm/commit/ab7f226d08acc67fbbbdb7c5aa0cea0415409d84
