### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstormports/wordpress-sandstorm#47]
So WordPress release 18 here can check for theme and plugin updates, but it can't download them: It uses cURL, and cURL doesn't trust the self-signed certificate. Not going to look at this tonight, but we'll need to convince the cURL to accept it.

**Comment by ocdtrekkie** [comment]
WordPress keeps it's own certificate bundle here: https://github.com/sandstormports/wordpress/tree/master/wp-includes/certificates

@zenhack My idea here is to symlink that directory in the read-only version of WordPress to a /var/certificates directory, and generate the proxy cert there. But the proxy cert is a .pem, and the bundle here is a .crt. Would you be able to advise me the best solution to hand WordPress what it is looking for, and the proxy what it needs?

**Comment by zenhack** [comment]
I *think* those are still pem encoded, just with a different file extension. So you can probably just set CA_CERT_PATH to the desired path (e.g. /var/certificates/ca-bundle.crt) and it will likely work.

**Comment by ocdtrekkie** [comment]
That was easy: https://github.com/sandstormports/wordpress-sandstorm/commit/8adaff076656bba5f1a353c5fc4de90ead5b7ca8

Thanks, Ian!
