### ISSUE TITLE
Failed to import Media during Wordpress xml Import

### ISSUE THREAD

**Issue by xet7** [sandstormports/wordpress-sandstorm#7]
_From @tiagoefreitas on September 11, 2015 10:33_

When importing a Wordpress export file, there is an option for it to download media from the original location. 
It gives the error:

Failed to import Media

_Copied from original issue: dwrensha/wordpress-sandstorm#10_

**Comment by xet7** [comment]
_From @paulproteus on September 11, 2015 17:9_

This is because the WordPress package has no ​access to the Internet to
download those images.

David, it'd be nice if there were a way we could fix these sorts of import
issues, or (alternately) warn people on the "Import" page in the Sandstorm
WordPress package that they'll have to import images separately, with some
info on how to do that (maybe a tool they can run on their own machine that
takes a WXR file and downloads the relevant images and then prepares a ZIP
file they can upload via some part of the WordPress interface).

**Comment by xet7** [comment]
_From @andru on October 4, 2015 20:40_

Just got stung by this.  Any hint on how to move the media over during an import?

**Comment by xet7** [comment]
_From @paulproteus on October 5, 2015 5:53_

So @zarvox, when @jparyani and I were thinking about a related problem, Jason realized that we could turn certain web page inputs into powerbox actions.

So one thing we could do is have the WordPress "Import WXR" functionality grant WordPress access to the HTTP resources named in the WXR.

This is a totally different way to think about powerbox UI, imho, and probably a really good one. I wonder if making such a thing work correctly would be something that makes sense to implement as part of your thinking about PowerBox UI.

Let me know what you think.

@andru for now I think this is blocked on a new Sandstorm feature but I hope we can do it soon.

**Comment by JamborJan** [comment]
Hey @ocdtrekkie can you give us some information about the current status of the power box feature? According to what I understand here is the problem, that the media is not imported during the import-process because Wordpress cannot reach the outside-the-grain world. Thats where we will have to use power box.

**Comment by ocdtrekkie** [comment]
There currently isn't a good way to do this. My hope is eventually you will be able to make a powerbox request to grant HTTP access to an arbitrary domain, but no such feature exists at present.

Currently if you can pull this client side through the user's browser, it would work, but that will eventually change.

**Comment by ocdtrekkie** [comment]
I'd really like to be able to do this with powerbox-http-proxy now that we have it, @zenhack. I don't think I really need a newer WordPress version, I just want this one to import well... I might have to see if it's buildable still.

**Comment by ocdtrekkie** [comment]
This is resolved as of #45. It's an issue filed eight years ago now, but someone finally got to it! Release coming probably after next Sandstorm release, since I probably need to submit an app ID replacement PR.

cc: @xet7 @paulproteus @JamborJan @tiagoefreitas @andru
